apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fast-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fast-api
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50