kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: fast-pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi